# Generated by Django 5.0 on 2023-12-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruceros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(default='Compañía X', max_length=100)),
                ('continente', models.CharField(default='Continente X', max_length=100)),
                ('precio', models.FloatField(default=5000)),
                ('puerto', models.CharField(choices=[('ID 1: Sudamerica', 'Sudamerica'), ('ID 2: Caribe', 'Caribe'), ('ID 3: Europa', 'Europa'), ('ID 4: Asia', 'Asia')], max_length=100)),
            ],
            options={
                'db_table': 'cruise_table',
            },
        ),
    ]
