# Generated by Django 4.2.7 on 2023-12-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruceros',
            name='compania',
            field=models.CharField(choices=[('MSC', 'MSC'), ('RYG', 'RYG'), ('Viking', 'Viking'), ('NCL', 'NCL'), ('Seabourn', 'Seabourn'), ('Star Cruises', 'Star Cruises'), ('Carnival', 'Carnival'), ('Costa', 'Costa'), ('AIDA', 'AIDA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cruceros',
            name='continente',
            field=models.CharField(choices=[('Sudamerica', 'Sudamerica'), ('Caribe', 'Caribe'), ('Europa', 'Europa'), ('Asia', 'Asia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cruceros',
            name='puerto',
            field=models.CharField(choices=[('Palermo', 'Palermo'), ('Bari', 'Bari'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Marsella', 'Marsella'), ('Lorient', 'Lorient'), ('La Habana', 'La Habana'), ('Puerto Príncipe', 'Puerto Príncipe'), ('Kingston', 'Kingston'), ('Hong Kong', 'Hong Kong'), ('Tokio', 'Tokio'), ('Buenos Aires', 'Buenos Aires'), ('Ushuaia', 'Ushuaia'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Recife', 'Recife')], max_length=100),
        ),
    ]
